export const theme = {
  colors: {
    bs: "var(--background-shade)",
    p: "var(--pink)",
    b: "var(--background)",
    v: "var(--violet)",
    vs: "var(--violet-shade)",
    va: "var(--violet-additional)",
    g: "var(--gradient)",
    fb: "var(--form-background)",
    w: "var(--white)",
    border: "var(--border)",
    buttonHover: "var(--button-hover)",
  },
  space: [0, 2, 4, 8, 16, 32, 60, 64, 110, 128, 256],
  fonts: {
    blinker: "'Blinker', sans-serif",
    roboto: "'Roboto', sans-serif",
  },
  fontSizes: {
    min: "12px",
    normalMin: "14px",
    normal: "16px",
    normalBig: "20px",
    normalMax: "32px",
    max: "64px",
  },
  fontWeights: {
    normal: 400,
    semiBold: 600,
    bold: 700,
  },
  lineHeights: {
    big: 2,
    body: 1.5,
    normal: 1.25,
    heading: 1.125,
  },
  borders: {
    none: "none",
    normal: "2px solid",
  },
  radii: {
    none: "0",
    normal: "4px",
    inputAuthForm: "24px",
    authForm: "32px",
    round: "50%",
  },
  size: {
    maxVH: "100vh",
    max: "100%",
    half: "50%",
    quarter: "25%",
    bar: "268px",
    authFormWidth: "636px",
    authFormHeight: "704px",
  },
  shadows: {},
};
